project_doc_fallback_filenames = ["CLAUDE .md"]

model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
hide_agent_reasoning = true

sandbox_mode = "workspace-write"
approval_policy = "on-request"

network_access = true
personality = "pragmatic"

web_search = "live"

[features]
multi_agent = true

[notice]
hide_gpt5_1_migration_prompt = true
hide_gpt-5.1-codex-max_migration_prompt = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
