model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
hide_agent_reasoning = true

sandbox_mode = "workspace-write"
approval_policy = "on-request"

network_access = true

[features]
web_search_request = true

[notice]
hide_gpt5_1_migration_prompt = true
hide_gpt-5.1-codex-max_migration_prompt = true
